// flow-typed signature: 25e18b31689728b953d1f04a1b783d05
// flow-typed version: <<STUB>>/@fortawesome/fontawesome-svg-core_v1.2.26/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/fontawesome-svg-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/fontawesome-svg-core' {
  declare module.exports: any;
}
