// flow-typed signature: b7626e86ebfe9e5cd8477d36e6dc019a
// flow-typed version: <<STUB>>/@fortawesome/pro-duotone-svg-icons_v5.12.0/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/pro-duotone-svg-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/pro-duotone-svg-icons' {
  declare module.exports: any;
}
