// flow-typed signature: 9f111d405e51ef2838329c17b6824b54
// flow-typed version: <<STUB>>/@fortawesome/pro-regular-svg-icons_v5.12.0/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/pro-regular-svg-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/pro-regular-svg-icons' {
  declare module.exports: any;
}
