// flow-typed signature: 59cefecd121ca0c6b6a6cce02aacaeb2
// flow-typed version: <<STUB>>/@fortawesome/react-fontawesome_v0.1.8/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/react-fontawesome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/react-fontawesome' {
  declare module.exports: any;
}
