import { PSA, DMF, CONTEXT } from '../Consts';
import { RESULT_CATEGORIES, COLORS, RELEASE_TYPES, CONDITION_TYPES } from '../DMFResultConsts';
import { PROPERTY_TYPES } from '../DataModelConsts';

export const COURT_PENN_1_1 = {
  [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
  [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
  [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
};

export const COURT_MINN_3_3 = {
  [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
  [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
  [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
  [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_MONTHLY
};

export const BOOKING_2_5 = {
  [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
  [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
  [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
  [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
};

export const COURT_PENN_4_5 = {
  [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
  [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
  [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
  [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_OR_BOND,
  [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY,
  [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
};

export const COURT_PENN_6_6 = {
  [RESULT_CATEGORIES.COLOR]: COLORS.RED,
  [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
  [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_AND_BOND,
  [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
  [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
};

const scenarios = [
  // STEP 2 DMFs
  {
    inputData: {
      [PSA.CURRENT_VIOLENT_OFFENSE]: 'true',
      [DMF.EXTRADITED]: 'true',
      [DMF.STEP_2_CHARGES]: 'true',
      [DMF.STEP_4_CHARGES]: 'true',
      [DMF.SECONDARY_RELEASE_CHARGES]: 'false'
    },
    scores: {
      [PROPERTY_TYPES.NVCA_FLAG]: [true],
      [PROPERTY_TYPES.NCA_SCALE]: [6],
      [PROPERTY_TYPES.FTA_SCALE]: [6]
    },
    expected: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_AND_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    }
  },
  {
    inputData: {
      [PSA.CURRENT_VIOLENT_OFFENSE]: 'true',
      [DMF.EXTRADITED]: 'false',
      [DMF.STEP_2_CHARGES]: 'false',
      [DMF.STEP_4_CHARGES]: 'false',
      [DMF.SECONDARY_RELEASE_CHARGES]: 'false'
    },
    scores: {
      [PROPERTY_TYPES.NVCA_FLAG]: [true],
      [PROPERTY_TYPES.NCA_SCALE]: [3],
      [PROPERTY_TYPES.FTA_SCALE]: [3]
    },
    expected: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_AND_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    }
  },
  {
    inputData: {
      [PSA.CURRENT_VIOLENT_OFFENSE]: 'true',
      [DMF.EXTRADITED]: 'true',
      [DMF.STEP_2_CHARGES]: 'false',
      [DMF.STEP_4_CHARGES]: 'false',
      [DMF.SECONDARY_RELEASE_CHARGES]: 'false'
    },
    scores: {
      [PROPERTY_TYPES.NVCA_FLAG]: [false],
      [PROPERTY_TYPES.NCA_SCALE]: [3],
      [PROPERTY_TYPES.FTA_SCALE]: [3]
    },
    expected: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_AND_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    }
  },
  {
    inputData: {
      [PSA.CURRENT_VIOLENT_OFFENSE]: 'false',
      [DMF.EXTRADITED]: 'false',
      [DMF.STEP_2_CHARGES]: 'true',
      [DMF.STEP_4_CHARGES]: 'false',
      [DMF.SECONDARY_RELEASE_CHARGES]: 'true'
    },
    scores: {
      [PROPERTY_TYPES.NVCA_FLAG]: [true],
      [PROPERTY_TYPES.NCA_SCALE]: [3],
      [PROPERTY_TYPES.FTA_SCALE]: [3]
    },
    expected: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_AND_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    }
  },

  // STEP 4 DMFs
  {
    inputData: {
      [PSA.CURRENT_VIOLENT_OFFENSE]: 'false',
      [DMF.EXTRADITED]: 'false',
      [DMF.STEP_2_CHARGES]: 'false',
      [DMF.STEP_4_CHARGES]: 'true',
      [DMF.SECONDARY_RELEASE_CHARGES]: 'true'
    },
    scores: {
      [PROPERTY_TYPES.NVCA_FLAG]: [false],
      [PROPERTY_TYPES.NCA_SCALE]: [3],
      [PROPERTY_TYPES.FTA_SCALE]: [3]
    },
    expected: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_TWICE_MONTHLY,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_TWICE_MONTHLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    }
  },
  {
    inputData: {
      [PSA.CURRENT_VIOLENT_OFFENSE]: 'false',
      [DMF.EXTRADITED]: 'false',
      [DMF.STEP_2_CHARGES]: 'false',
      [DMF.STEP_4_CHARGES]: 'false',
      [DMF.SECONDARY_RELEASE_CHARGES]: 'true'
    },
    scores: {
      [PROPERTY_TYPES.NVCA_FLAG]: [true],
      [PROPERTY_TYPES.NCA_SCALE]: [3],
      [PROPERTY_TYPES.FTA_SCALE]: [3]
    },
    expected: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_TWICE_MONTHLY,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_TWICE_MONTHLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    }
  },
  {
    inputData: {
      [PSA.CURRENT_VIOLENT_OFFENSE]: 'false',
      [DMF.EXTRADITED]: 'false',
      [DMF.STEP_2_CHARGES]: 'false',
      [DMF.STEP_4_CHARGES]: 'true',
      [DMF.SECONDARY_RELEASE_CHARGES]: 'true'
    },
    scores: {
      [PROPERTY_TYPES.NVCA_FLAG]: [false],
      [PROPERTY_TYPES.NCA_SCALE]: [1],
      [PROPERTY_TYPES.FTA_SCALE]: [1]
    },
    expected: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_MONTHLY
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_MONTHLY
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    }
  },
  {
    inputData: {
      [PSA.CURRENT_VIOLENT_OFFENSE]: 'false',
      [DMF.EXTRADITED]: 'false',
      [DMF.STEP_2_CHARGES]: 'false',
      [DMF.STEP_4_CHARGES]: 'true',
      [DMF.SECONDARY_RELEASE_CHARGES]: 'true'
    },
    scores: {
      [PROPERTY_TYPES.NVCA_FLAG]: [false],
      [PROPERTY_TYPES.NCA_SCALE]: [2],
      [PROPERTY_TYPES.FTA_SCALE]: [5]
    },
    expected: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_OR_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    }
  },
  {
    inputData: {
      [PSA.CURRENT_VIOLENT_OFFENSE]: 'false',
      [DMF.EXTRADITED]: 'false',
      [DMF.STEP_2_CHARGES]: 'false',
      [DMF.STEP_4_CHARGES]: 'true',
      [DMF.SECONDARY_RELEASE_CHARGES]: 'true'
    },
    scores: {
      [PROPERTY_TYPES.NVCA_FLAG]: [false],
      [PROPERTY_TYPES.NCA_SCALE]: [5],
      [PROPERTY_TYPES.FTA_SCALE]: [2]
    },
    expected: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_AND_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    }
  },
  {
    inputData: {
      [PSA.CURRENT_VIOLENT_OFFENSE]: 'false',
      [DMF.EXTRADITED]: 'false',
      [DMF.STEP_2_CHARGES]: 'false',
      [DMF.STEP_4_CHARGES]: 'true',
      [DMF.SECONDARY_RELEASE_CHARGES]: 'true'
    },
    scores: {
      [PROPERTY_TYPES.NVCA_FLAG]: [false],
      [PROPERTY_TYPES.NCA_SCALE]: [6],
      [PROPERTY_TYPES.FTA_SCALE]: [6]
    },
    expected: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_AND_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    }
  },

  // BOOKING EXCEPTION DMFs
  {
    inputData: {
      [PSA.CURRENT_VIOLENT_OFFENSE]: 'false',
      [DMF.EXTRADITED]: 'false',
      [DMF.STEP_2_CHARGES]: 'false',
      [DMF.STEP_4_CHARGES]: 'false',
      [DMF.SECONDARY_RELEASE_CHARGES]: 'true'
    },
    scores: {
      [PROPERTY_TYPES.NVCA_FLAG]: [false],
      [PROPERTY_TYPES.NCA_SCALE]: [1],
      [PROPERTY_TYPES.FTA_SCALE]: [1]
    },
    expected: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 0,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR_RELEASE
      }
    }
  },
  {
    inputData: {
      [PSA.CURRENT_VIOLENT_OFFENSE]: 'false',
      [DMF.EXTRADITED]: 'false',
      [DMF.STEP_2_CHARGES]: 'false',
      [DMF.STEP_4_CHARGES]: 'false',
      [DMF.SECONDARY_RELEASE_CHARGES]: 'true'
    },
    scores: {
      [PROPERTY_TYPES.NVCA_FLAG]: [false],
      [PROPERTY_TYPES.NCA_SCALE]: [2],
      [PROPERTY_TYPES.FTA_SCALE]: [5]
    },
    expected: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR_RELEASE
      }
    }
  },
  {
    inputData: {
      [PSA.CURRENT_VIOLENT_OFFENSE]: 'false',
      [DMF.EXTRADITED]: 'false',
      [DMF.STEP_2_CHARGES]: 'false',
      [DMF.STEP_4_CHARGES]: 'false',
      [DMF.SECONDARY_RELEASE_CHARGES]: 'true'
    },
    scores: {
      [PROPERTY_TYPES.NVCA_FLAG]: [false],
      [PROPERTY_TYPES.NCA_SCALE]: [3],
      [PROPERTY_TYPES.FTA_SCALE]: [4]
    },
    expected: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_MONTHLY
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_MONTHLY
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR_RELEASE
      }
    }
  },
  {
    inputData: {
      [PSA.CURRENT_VIOLENT_OFFENSE]: 'false',
      [DMF.EXTRADITED]: 'false',
      [DMF.STEP_2_CHARGES]: 'false',
      [DMF.STEP_4_CHARGES]: 'false',
      [DMF.SECONDARY_RELEASE_CHARGES]: 'true'
    },
    scores: {
      [PROPERTY_TYPES.NVCA_FLAG]: [false],
      [PROPERTY_TYPES.NCA_SCALE]: [4],
      [PROPERTY_TYPES.FTA_SCALE]: [4]
    },
    expected: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_TWICE_MONTHLY,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_TWICE_MONTHLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR_RELEASE
      }
    }
  },
  {
    inputData: {
      [PSA.CURRENT_VIOLENT_OFFENSE]: 'false',
      [DMF.EXTRADITED]: 'false',
      [DMF.STEP_2_CHARGES]: 'false',
      [DMF.STEP_4_CHARGES]: 'false',
      [DMF.SECONDARY_RELEASE_CHARGES]: 'true'
    },
    scores: {
      [PROPERTY_TYPES.NVCA_FLAG]: [false],
      [PROPERTY_TYPES.NCA_SCALE]: [4],
      [PROPERTY_TYPES.FTA_SCALE]: [5]
    },
    expected: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_OR_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    }
  },
  {
    inputData: {
      [PSA.CURRENT_VIOLENT_OFFENSE]: 'false',
      [DMF.EXTRADITED]: 'false',
      [DMF.STEP_2_CHARGES]: 'false',
      [DMF.STEP_4_CHARGES]: 'false',
      [DMF.SECONDARY_RELEASE_CHARGES]: 'true'
    },
    scores: {
      [PROPERTY_TYPES.NVCA_FLAG]: [false],
      [PROPERTY_TYPES.NCA_SCALE]: [4],
      [PROPERTY_TYPES.FTA_SCALE]: [5]
    },
    expected: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_OR_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    }
  },

  // REGULAR DMFs
  {
    inputData: {
      [PSA.CURRENT_VIOLENT_OFFENSE]: 'false',
      [DMF.EXTRADITED]: 'false',
      [DMF.STEP_2_CHARGES]: 'false',
      [DMF.STEP_4_CHARGES]: 'false',
      [DMF.SECONDARY_RELEASE_CHARGES]: 'false'
    },
    scores: {
      [PROPERTY_TYPES.NVCA_FLAG]: [false],
      [PROPERTY_TYPES.NCA_SCALE]: [1],
      [PROPERTY_TYPES.FTA_SCALE]: [1]
    },
    expected: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 0,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR_RELEASE
      }
    }
  },
  {
    inputData: {
      [PSA.CURRENT_VIOLENT_OFFENSE]: 'false',
      [DMF.EXTRADITED]: 'false',
      [DMF.STEP_2_CHARGES]: 'false',
      [DMF.STEP_4_CHARGES]: 'false',
      [DMF.SECONDARY_RELEASE_CHARGES]: 'false'
    },
    scores: {
      [PROPERTY_TYPES.NVCA_FLAG]: [false],
      [PROPERTY_TYPES.NCA_SCALE]: [3],
      [PROPERTY_TYPES.FTA_SCALE]: [5]
    },
    expected: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    }
  },
  {
    inputData: {
      [PSA.CURRENT_VIOLENT_OFFENSE]: 'false',
      [DMF.EXTRADITED]: 'false',
      [DMF.STEP_2_CHARGES]: 'false',
      [DMF.STEP_4_CHARGES]: 'false',
      [DMF.SECONDARY_RELEASE_CHARGES]: 'false'
    },
    scores: {
      [PROPERTY_TYPES.NVCA_FLAG]: [false],
      [PROPERTY_TYPES.NCA_SCALE]: [4],
      [PROPERTY_TYPES.FTA_SCALE]: [5]
    },
    expected: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_OR_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    }
  },
  {
    inputData: {
      [PSA.CURRENT_VIOLENT_OFFENSE]: 'false',
      [DMF.EXTRADITED]: 'false',
      [DMF.STEP_2_CHARGES]: 'false',
      [DMF.STEP_4_CHARGES]: 'false',
      [DMF.SECONDARY_RELEASE_CHARGES]: 'false'
    },
    scores: {
      [PROPERTY_TYPES.NVCA_FLAG]: [false],
      [PROPERTY_TYPES.NCA_SCALE]: [4],
      [PROPERTY_TYPES.FTA_SCALE]: [6]
    },
    expected: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_AND_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    }
  },
  {
    inputData: {
      [PSA.CURRENT_VIOLENT_OFFENSE]: 'false',
      [DMF.EXTRADITED]: 'false',
      [DMF.STEP_2_CHARGES]: 'false',
      [DMF.STEP_4_CHARGES]: 'false',
      [DMF.SECONDARY_RELEASE_CHARGES]: 'false'
    },
    scores: {
      [PROPERTY_TYPES.NVCA_FLAG]: [false],
      [PROPERTY_TYPES.NCA_SCALE]: [6],
      [PROPERTY_TYPES.FTA_SCALE]: [6]
    },
    expected: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_AND_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    }
  }
];

export default scenarios;
