/*
 * @flow
 */

export const LOAD_PSAS_BY_DATE_REQUEST :string = 'LOAD_PSAS_BY_DATE_REQUEST';
export const LOAD_PSAS_BY_DATE_SUCCESS :string = 'LOAD_PSAS_BY_DATE_SUCCESS';
export const LOAD_PSAS_BY_DATE_FAILURE :string = 'LOAD_PSAS_BY_DATE_FAILURE';

export const DOWNLOAD_PSA_REVIEW_PDF_REQUEST :string = 'DOWNLOAD_PSA_REVIEW_PDF_REQUEST';
export const DOWNLOAD_PSA_REVIEW_PDF_SUCCESS :string = 'DOWNLOAD_PSA_REVIEW_PDF_SUCCESS';
export const DOWNLOAD_PSA_REVIEW_PDF_FAILURE :string = 'DOWNLOAD_PSA_REVIEW_PDF_FAILURE';

export const UPDATE_SCORES_AND_RISK_FACTORS_REQUEST :string = 'UPDATE_SCORES_AND_RISK_FACTORS_REQUEST';
export const UPDATE_SCORES_AND_RISK_FACTORS_SUCCESS :string = 'UPDATE_SCORES_AND_RISK_FACTORS_SUCCESS';
export const UPDATE_SCORES_AND_RISK_FACTORS_FAILURE :string = 'UPDATE_SCORES_AND_RISK_FACTORS_FAILURE';
