// flow-typed signature: 158ed5bbfa99cb415343d78a1e5b760f
// flow-typed version: <<STUB>>/auth0-lock_v11.25.1/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'auth0-lock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'auth0-lock' {
  declare module.exports: any;
}
