// flow-typed signature: 0052ff950b19d8dd16e9e395424f3f22
// flow-typed version: <<STUB>>/jwt-decode_v2.2.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jwt-decode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jwt-decode' {
  declare module.exports: any;
}
