// flow-typed signature: 03ce911c60a8ae846c290a7d205e718f
// flow-typed version: <<STUB>>/react-select_v2.4.3/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-select' {
  declare module.exports: any;
}
