/*
* @flow
*/

import Immutable from 'immutable';

import { getEntityKeyId } from '../DataUtils';
import { PROPERTY_TYPES } from './DataModelConsts';

export const ODYSSEY_VIOLENT_STATUTES = [
  '22-4-1',
  '22-4-2',
  '22-8-12',
  '22-10-1',
  '22-10-5',
  '22-10-5.1',
  '22-10-6',
  '22-10-6.1',
  '22-11a-2',
  '22-14-20',
  '22-14a-5',
  '22-14a-6',
  '22-14a-11',
  '22-14a-19',
  '22-14a-20',
  '22-16-1',
  '22-16-1.1',
  '22-16-4',
  '22-16-5',
  '22-16-7',
  '22-16-15',
  '22-16-20',
  '22-16-41',
  '22-17-6',
  '22-18-1',
  '22-18-1.05',
  '22-18-1.1',
  '22-18-1.2',
  '22-18-1.3',
  '22-18-1.4',
  '22-18-1.5',
  '22-18-26',
  '22-18-26.1',
  '22-18-29',
  '22-18-29.1',
  '22-18-31',
  '22-18-37',
  '22-19-1.1',
  '22-19-1',
  '22-19a-1',
  '22-19a-7',
  '22-19-17',
  '22-22-1',
  '22-22-24.3',
  '22-22-28',
  '22-22-29',
  '22-22-7.2',
  '22-22-7.4',
  '22-22-7',
  '22-22-7.7',
  '22-24a-5',
  '22-30-1',
  '22-30-6',
  '22-30-7',
  '22-32-1',
  '22-33-10',
  '22-33-9.1',
  '22-46-2',
  '22-49-1',
  '22-49-2',
  '22-49-3',
  '22-4a-1',
  '26-10-1',
  '26-10-30',
  '26-10-32',
];

export const ODYSSEY_EXCEPTION_DESCRIPTIONS = {
  '22-46-2': ['Emotional or psychological abuse of Disabled Adult']
};

export const ODYSSEY_VIOLENT_CHARGES = {
  '22-4-1': [
    'ATTEMPTS TO COMMIT CRIME'
  ],
  '22-4-2': [
    'ATTEMPT RESULTING IN COMMISSION OF OTHER CRIME'
  ],
  '22-8-12': [
    'TERRORISM'
  ],
  '22-10-1': [
    'RIOT'
  ],
  '22-10-5': [
    'AGGRAVATED RIOT'
  ],
  '22-10-5.1': [
    'ATTEMPTED RIOT',
    'ATTEMPTED AGGRAVATED RIOT'
  ],
  '22-10-6': [
    'SOLICIT VIOLENCE/PARTICIPANT'
  ],
  '22-10-6.1': [
    'SOLICIT VIOLENCE/NONPARTICIPANT'
  ],
  '22-11a-2': [
    'ESCAPE BY PRISONER-FIRST DEGREE'
  ],
  '22-14-20': [
    'DISCHARGE FIREARM AT STUCTURE/MOTOR  VEHICLE'
  ],
  '22-14a-5': [
    'CARRY OR PLACE EXPLOSIVES ON PUBLIC CONVEYANCE'
  ],
  '22-14a-6': [
    'POSSESS EXPLOSIVES WITH CRIMINAL INTENT'
  ],
  '22-14a-11': [
    'INTENTIONAL USE OF EXPLOSIVE TO CAUSE BODILY HARM'
  ],
  '22-14a-19': [
    'DESTROY STRUCTURE WITH EXPLOSIVES,ENDANGER LIFE'
  ],
  '22-14a-20': [
    'CARRY OR PLACE EXPLOSIVES SO AS TO ENDANGER LIFE'
  ],
  '22-16-1': [
    'HOMICIDE DEFINED'
  ],
  '22-16-1.1': [
    'FETAL HOMICIDE'
  ],
  '22-16-4': [
    'MURDER-1ST DEGREE (FELONY)',
    'DOM ABUSE - MURDER- 1ST DEGREE (FELONY)'
  ],
  '22-16-5': [
    'PREMEDITATED DESIGN TO EFFECT THE DEATH DEFINED'
  ],
  '22-16-7': [
    'FETAL HOMICIDE',
    'DOM ABUSE - MURDER-2ND DEGREE'
  ],
  '22-16-15': [
    'MANSLAUGHTER - 1ST DEGREE',
    'DOM ABUSE - MANSLAUGHTER - 1ST DEGREE'
  ],
  '22-16-20': [
    'MANSLAUGHTER-2ND DEGREE',
    'DOM ABUSE - MANSLAUGHTER - 2ND DEGREE'
  ],
  '22-16-41': [
    'VEHICULAR HOMICIDE',
    'DOM ABUSE - VEHICULAR HOMICIDE'
  ],
  '22-17-6': [
    'INJURE MOTHER TO KILL FETUS'
  ],
  '22-18-1': [
    'SIMPLE ASSAULT',
    'SIMPLE ASSAULT ATTEMPT TO CAUSE BODILY INJURY',
    'DOM ABUSE SIMPLE ASSAULT ATTEMPT TO CAUSE BODILY INJURY',
    'SIMPLE ASSAULT ATTEMPT TO CAUSE BODILY INJURY 3RD OR SUBSEQUENT OFFENSE',
    'DOM ABUSE SIMPLE ASSAULT ATTEMPT TO CAUSE BODILY INJURY 3RD OR SUBSEQUENT OFFENSE',
    'SIMPLE ASSAULT RECKLESSLY CAUSES BODILY INJURY',
    'DOM ABUSE SIMPLE ASSAULT RECKLESSLY CAUSES BODILY INJURY',
    'SIMPLE ASSAULT RECKLESSLY CAUSES BODILY INJURY 3RD OR SUBSEQUENT OFFENSE',
    'DOM ABUSE SIMPLE ASSAULT RECKLESSLY CAUSES BODILY INJURY 3RD OR SUBSEQUENT OFFENSE',
    'SIMPLE ASSAULT NEGLIGENTLY CAUSES BODILY INJURY',
    'DOM ABUSE SIMPLE ASSAULT NEGLIGENTLY CAUSES BODILY INJURY',
    'SIMPLE ASSAULT NEGLIGENTLY CAUSES BODILY INJURY 3RD OR SUBSEQUENT OFFENSE',
    'DOM ABUSE SIMPLE ASSAULT NEGLIGENTLY CAUSES BODILY INJURY 3RD OR SUBSEQUENT OFFENSE',
    'SIMPLE ASSAULT ATTEMPT TO PUT ANOTHER IN FEAR OF BODILY HARM',
    'DOM ABUSE SIMPLE ASSAULT ATTEMPT TO PUT ANOTHER IN FEAR OF BODILY HARM',
    'SIMPLE ASSAULT ATTEMPT TO PUT ANOTHER IN FEAR OF BODILY HARM 3RD OR SUBSEQUENT OFFENSE',
    'DOM ABUSE SIMPLE ASSAULT ATTEMPT TO PUT ANOTHER IN FEAR OF BODILY HARM 3RD OR SUBSEQUENT OFFENSE',
    'SIMPLE ASSAULT INTENTIONALLY CAUSE BODILY INJURY',
    'DOM ABUSE SIMPLE ASSAULT INTENTIONALLY CAUSE BODILY INJURY',
    'SIMPLE ASSAULT INTENTIONALLY CAUSE BODILY INJURY 3RD OR SUBSEQUENT OFFENSE',
    'DOM ABUSE SIMPLE ASSAULT INTENTIONALLY CAUSE BODILY INJURY 3RD OR SUBSEQUENT OFFENSE'
  ],
  '22-18-1.05': [
    'AGGRAVATED ASSAULT AGAINST LAW ENFORCEMENT OFFICER',
    'SIMPLE ASSAULT AGAINST LAW ENFORCEMENT OFFICER'
  ],
  '22-18-1.1': [
    'AGGRAVATED ASSAULT',
    'DOM ABUSE AGGRAVATED ASSAULT - BODILY INJURY WITH INDIFFERENCE TO HUMAN LIFE',
    'AGGRAVATED ASSAULT - BODILY INJURY WITH INDIFFERENCE TO HUMAN LIFE',
    'DOM ABUSE AGGRAVATED ASSAULT - BODILY INJURY WITH DANGEROUS WEAPON',
    'AGGRAVATED ASSAULT - BODILY INJURY WITH DANGEROUS WEAPON',
    'DOM ABUSE AGGRAVATED ASSAULT - SERIOUS BODILY INJURY',
    'AGGRAVATED ASSAULT - SERIOUS BODILY INJURY',
    'DOM ABUSE AGGRAVATED ASSAULT - DEADLY WEAPON',
    'AGGRAVATED ASSAULT - DEADLY WEAPON',
    'DOM ABUSE AGGRAVATED ASSAULT - CHOKING',
    'AGGRAVATED ASSAULT - CHOKING'
  ],
  '22-18-1.2': [
    'CRIMINAL BATTERY OF AN UNBORN CHILD'
  ],
  '22-18-1.3': [
    'AGGRAVATED BATTERY OF UNBORN CHILD'
  ],
  '22-18-1.4': [
    'AGGRAVATED BATTERY OF AN INFANT',
    'SUBSEQUENT AGGRAVATED BATTERY OF AN INFANT'
  ],
  '22-18-1.5': [
    'ASSAULT WITH INTENT TO CAUSE SERIOUS PERMANENT DISFIGUREMENT',
    'DOM ABUSE ASSAULT WITH INTENT TO CAUSE SERIOUS PERMANENT DISFIGUREMENT'
  ],
  '22-18-26': [
    'ASSAULTS BY INMATES'
  ],
  '22-18-26.1': [
    'INTENTIONAL CAUSING CONTACT W/BODILY FLUIDS/HUMAN WASTE'
  ],
  '22-18-29': [
    'ASSAULT BY ADULT CONFINED IN JAIL'
  ],
  '22-18-29.1': [
    'ASSAULT BY JUVENILE CONFINED IN DETENTION FACILITY'
  ],
  '22-18-31': [
    'INTENTIONAL EXPOSURE TO HIV INFECTION'
  ],
  '22-18-37': [
    'FEMALE GENITAL MUTILATION - degreeFieldIsFelony'
  ],
  '22-19-1.1': [
    'AGGRAVATED KIDNAPPING-2ND DEGREE',
    'DOM ABUSE - AGGRAVATED KIDNAPPING - 2ND DEGREE',
    'DOM ABUSE - KIDNAPPING - 2ND DEGREE',
    'KIDNAPPING-2ND DEGREE'
  ],
  '22-19-1': [
    'DOM ABUSE - AGGRAVATED KIDNAPPING - 1ST DEGREE',
    'AGGRAVATED KIDNAPPING-1ST DEGREE',
    'DOM ABUSE - KIDNAPPING - 1ST DEGREE',
    'KIDNAPPING-1ST DEGREE'
  ],
  '22-19a-1': [
    'DOM ABUSE - STALKING - SECOND OR SUBSEQUENT CONVICTION',
    'STALKING-SECOND OR SUBSEQUENT CONVICTION',
    'DOM ABUSE - STALKING',
    'STALKING'
  ],
  '22-19a-7': [
    'DOM ABUSE - STALKING A CHILD TWELVE OR YOUNGER',
    'STALKING A CHILD TWELVE OR YOUNGER'
  ],
  '22-19-17': [
    'FALSE IMPRISONMENT'
  ],
  '22-22-1': [
    'DOM ABUSE - RAPE 1ST DEGREE - LESS THAN THIRTEEN',
    'RAPE 1ST DEGREE-LESS THAN 13',
    'DOM ABUSE - RAPE 2ND DEGREE - USE OF FORCE, COERCION OR THREATS',
    'RAPE 2ND DEGREE USE OF FORCE, COERCION, OR THREATS',
    'RAPE 3RD DEGREE PHYSICAL/MENTAL INCAPACITY',
    'DOM ABUSE - RAPE 3RD DEGREE - PHYSICAL/MENTAL INCAPACITY',
    'DOM ABUSE - RAPE 3RD DEGREE - INCAPABLE INTOX, MIND ALTER, ETC.',
    'RAPE 3RD DEGREE INCAPABLE INTOX, MIND ALTER, ETC',
    'RAPE 4TH DEGREE-VICTIM 13 BUT LESS THAN 16',
    'DOM ABUSE - RAPE 4TH DEGREE - VICTIM 13, BUT LESS THAN SIXTEEN'
  ],
  '22-22-24.3': [
    'SEXUAL EXPLOITATION OF A MINOR'
  ],
  '22-22-28': [
    'SEXUAL CONTACT BY PSYCHOTHERAPIST'
  ],
  '22-22-29': [
    'SEXUAL PENETRATION BY PSYCHOTHERAPIST'
  ],
  '22-22-7.2': [
    'SEXUAL CONTACT INCAPABLE OF CONSENT',
    'DOM ABUSE - SEXUAL CONTACT INCAPABLE OF CONSENT'
  ],
  '22-22-7.4': [
    'DOM ABUSE - SEXUAL CONTACT WITHOUT CONSENT CAPABLE OF CONSENT',
    'SEXUAL CONTACT W/O CONSENT CAPABLE OF CONSENT'
  ],
  '22-22-7': [
    'DOM ABUSE - SEXUAL CONTACT - AGE DIFFERENCE LESS THAN 5 YEARS',
    'DOM ABUSE - SEXUAL CONTACT CHILD UNDER 16',
    'DOM ABUSE - SEXUAL CONTACT WITH CHILD UNDER FIFTEEN',
    'SEXUAL CONTACT CHILD UNDER 16',
    'DOM ABUSE - SEXUAL CONTACT CHILD UNDER FIFTEEN',
    'SEXUAL CONTACT-AGE DIFF LESS 5 YRS'
  ],
  '22-24a-5': [
    'SOLICITATION OF A MINOR'
  ],
  '22-30-1': [
    'ROBBERY DEFINED'
  ],
  '22-30-6': [
    'ROBBERY IN THE 2ND DEGREE(F4)',
    'ROBBERY IN THE FIRST DEGREE(F2)'
  ],
  '22-30-7': [
    'DOM ABUSE - ROBBERY - 1ST DEGREE',
    'DOM ABUSE - ROBBERY - 2ND DEGREE',
    'ROBBERY-1ST DEGREE',
    'ROBBERY-2ND DEGREE'
  ],
  '22-32-1': [
    'DOM ABUSE - BURGLARY - 1ST DEGREE',
    'BURGLARY-1ST DEGREE'
  ],
  '22-33-10': [
    'BURN WITHIN STRUCTURE WHERE PERSON IS CONFINED'
  ],
  '22-33-9.1': [
    'DOM ABUSE - FIRST DEGREE ARSON',
    'FIRST DEGREE ARSON'
  ],
  '22-46-2': [
    'ABUSE OR NEGLECTS A DISABLED ADULT OR ELDER'
  ],
  '22-49-1': [
    'HUMAN TRAFFICKING PROHIBITED'
  ],
  '22-49-2': [
    'FIRST DEGREE HUMAN TRAFFICKING'
  ],
  '22-49-3': [
    'SECOND DEGREE HUMAN TRAFFICKING'
  ],
  '22-4a-1': [
    'DOM ABUSE - CRIMINAL SOLICITATION OF CLASS 1 FELONY',
    'DOM ABUSE - CRIMINAL SOLICITATION OF CLASS 2 FELONY',
    'DOM ABUSE - CRIMINAL SOLICITATION OF CLASS 3 FELONY',
    'DOM ABUSE - CRIMINAL SOLICITATION OF CLASS 4 FELONY',
    'DOM ABUSE - CRIMINAL SOLICITATION OF CLASS 5 FELONY',
    'DOM ABUSE - CRIMINAL SOLICITATION OF CLASS 6 FELONY',
    'DOM ABUSE - CRIMINAL SOLICITATION OF CLASS A, B, OR C FELONY',
    'CRIMINAL SOLICITATION OF CLASS 1 FELONY',
    'CRIMINAL SOLICITATION OF CLASS 2 FELONY',
    'CRIMINAL SOLICITATION OF CLASS 3 FELONY',
    'CRIMINAL SOLICITATION OF CLASS 4 FELONY',
    'CRIMINAL SOLICITATION OF CLASS 5 FELONY',
    'CRIMINAL SOLICITATION OF CLASS 6 FELONY',
    'CRIMINAL SOLICITATION OF CLASS A,B OR C FELONY'
  ],
  '26-10-1': [
    'DOM ABUSE - ABUSE/CRUELTY MINOR - LESS THAN SEVEN YEARS OF AGE',
    'ABUSE/CRUELTY MINOR-LESS 7 YRS AGE',
    'CHILD ABUSE',
    'DOM ABUSE - CHILD ABUSE'
  ],
  '26-10-30': [
    'PARENT/GUARDIAN PERMIT PHYSICAL/SEXUAL ABUSE OF CHILD'
  ],
  '26-10-32': [
    'BRANDING OF A MINOR'
  ]
};

export const GUILTY_DISPOSITIONS = [
  'Convicted at Trial',
  'Convicted at Trial/Punishment Enhanced by Part II Info',
  'Conviction-Death Penalty',
  'Deferred Imposition of Sentence',
  'Guilty But Mentally Ill',
  'Jail',
  'Judgment on Plea of Guilty',
  'Punishment Enhanced by Part II Information',
  'Restitution',
  'Stipulate to Facts-Found Guilty',
  'Suspended Execution of Sentence',
  'Suspended Execution of Sentence Revoked and Released',
  'Suspended Execution Revocation to Jail',
  'Suspended Execution Revocation to Penitentiary',
  'Suspended Execution Revocation/Continued on Probation',
  'Stipulate to Facts-Found Guilty',
  'Suspended Execution of Sentence',
  'Suspended Execution of Sentence Revoked and Released',
  'Suspended Imposition of Sentence',
  'Suspended Imposition Revocation to Jail',
  'Suspended Imposition Revocation to Penitentiary',
  'Suspended Imposition Revocation/Continued on Probation',
  'Suspended Imposition Revoked/Released'
];

export const MISDEMEANOR_CHARGE_LEVEL_CODES :Set<string> = Immutable.Set([
  'M1',
  'M2'
]);

export const CHARGE_TYPES = {
  ARREST: 'arrest',
  COURT: 'court'
};

export const CHARGE_HEADERS = {
  STATUTE: 'Statute',
  DESCRIPTION: 'Description',
  DEGREE: 'Degree',
  DEGREE_SHORT: '(short)',
  VIOLENT: 'Violent',
  STEP_2: 'Step 2',
  STEP_4: 'Step 4',
  BHE: 'BHE',
  BRE: 'BRE'
};

export const getChargeConsts = (charge) => {
  const degree = charge.getIn([PROPERTY_TYPES.REFERENCE_CHARGE_LEVEL, 0], '');
  const degreeShort = charge.getIn([PROPERTY_TYPES.REFERENCE_CHARGE_DEGREE, 0], '');
  const description = charge.getIn([PROPERTY_TYPES.REFERENCE_CHARGE_DESCRIPTION, 0], '');
  const entityKeyId = getEntityKeyId(charge);
  const isViolent = charge.getIn([PROPERTY_TYPES.CHARGE_IS_VIOLENT, 0], false);
  const isStep2 = charge.getIn([PROPERTY_TYPES.CHARGE_DMF_STEP_2, 0], false);
  const isStep4 = charge.getIn([PROPERTY_TYPES.CHARGE_DMF_STEP_4, 0], false);
  const isBRE = charge.getIn([PROPERTY_TYPES.BRE, 0], false);
  const isBHE = charge.getIn([PROPERTY_TYPES.BHE, 0], false);
  const statute = charge.getIn([PROPERTY_TYPES.REFERENCE_CHARGE_STATUTE, 0], '');
  return {
    degree,
    degreeShort,
    description,
    entityKeyId,
    isViolent,
    isStep2,
    isStep4,
    isBRE,
    isBHE,
    statute
  };
};
