const DISPOSITIONS = [
  'Acquittal by Motion',
  'Acquitted at Trial',
  'Acquitted for Mental Illness',
  'Contested-Extradition Denied',
  'Contested-Extradition Ordered',
  'Convicted at Trial',
  'Convicted at Trial/Punishment Enhanced by Part II Info',
  'Conviction-Death Penalty',
  'Dismissal-Defendant not Available',
  'Dismissal-Deferred Prosecution',
  'Dismissal-Reduction',
  'Dismissed for Lack of Progress',
  'Dismissed-Motion by Court',
  'Dismissed-Motion by Defendant',
  'Dismissed-Motion by Prosecutor',
  'Dismissed-Not Timely Filed',
  'Dismissed-Prosecutor/Clerical Error',
  'Extradited',
  'Guilty But Mentally Ill',
  'Hung Jury',
  'Jail',
  'Judgment on Plea of Guilty',
  'Judgment Vacated',
  'Mistrial',
  'No Formal Action',
  'Not Sustained at Prelim/Grand Jury',
  'Pardoned',
  'Petition Dismissed',
  'Petition Not Sustained',
  'Petition Sustained',
  'Punishment Enhanced by Part II Information',
  'Recharged',
  'Recharged-by Indictment',
  'Recharged-by Information',
  'Redocketed/Remanded/Bound Over',
  'Refer to States Attorney for Diversion',
  'Restitution',
  'Revoked Suspended Imposition of Adjudication',
  'Stipulate to Facts-Found Guilty',
  'Suspended Execution of Sentence',
  'Suspended Execution of Sentence Revoked and Released',
  'Suspended Execution Revocation to Jail',
  'Suspended Execution Revocation to Penitentiary',
  'Suspended Execution Revocation/Continued on Probation',
  'Suspended Imposition of Adjudication',
  'Suspended Imposition of Sentence',
  'Suspended Imposition Revocation to Jail',
  'Suspended Imposition Revocation to Penitentiary',
  'Suspended Imposition Revocation/Continued on Probation',
  'Suspended Imposition Revoked/Released',
  'Termination of Parental Rights',
  'Transfer to Criminal Docket',
  'Transferred to Mental Health Agency',
  'Transferred to Tribal Court'
];

export default DISPOSITIONS;
