/*
 * @flow
 */
import { CONTEXT } from './Consts';
import { PROPERTY_TYPES } from './DataModelConsts';

export const COLORS = {
  DARK_GREEN: 'DARK_GREEN',
  LIGHT_GREEN: 'LIGHT_GREEN',
  YELLOW: 'YELLOW',
  ORANGE: 'ORANGE',
  RED: 'RED'
};

export const RELEASE_TYPES = {
  RELEASE: 'RELEASE',
  RELEASE_WITH_CONDITIONS: 'RELEASE_WITH_CONDITIONS',
  MAXIMUM_CONDITIONS: 'MAXIMUM_CONDITIONS'
};

export const CONDITION_TYPES = {
  PR: 'PR',
  PR_RELEASE: 'PR_RELEASE',
  EM_OR_BOND: 'EM_OR_BOND',
  EM_AND_BOND: 'EM_AND_BOND',
  CHECKIN_WEEKLY: 'CHECKIN_WEEKLY',
  CHECKIN_WEEKLY_AT_LEAST: 'CHECKIN_WEEKLY_AT_LEAST',
  CHECKIN_MONTHLY: 'CHECKIN_MONTHLY',
  CHECKIN_TWICE_MONTHLY: 'CHECKIN_TWICE_MONTHLY',
  IF_APPLICABLE_247: 'IF_APPLICABLE_247',
  HOLD_PENDING_JUDICIAL_REVIEW: 'HOLD_PENDING_JUDICIAL_REVIEW'
};

export const RESULT_CATEGORIES :Object = {
  COLOR: 'COLOR',
  RELEASE_TYPE: 'RELEASE_TYPE',
  CONDITIONS_LEVEL: 'CONDITIONS_LEVEL',
  CONDITION_1: 'CONDITION_1',
  CONDITION_2: 'CONDITION_2',
  CONDITION_3: 'CONDITION_3'
};

export const RESULT_CATEGORIES_TO_PROPERTY_TYPES = {
  [RESULT_CATEGORIES.COLOR]: PROPERTY_TYPES.COLOR,
  [RESULT_CATEGORIES.RELEASE_TYPE]: PROPERTY_TYPES.RELEASE_TYPE,
  [RESULT_CATEGORIES.CONDITIONS_LEVEL]: PROPERTY_TYPES.CONDITIONS_LEVEL,
  [RESULT_CATEGORIES.CONDITION_1]: PROPERTY_TYPES.CONDITION_1,
  [RESULT_CATEGORIES.CONDITION_2]: PROPERTY_TYPES.CONDITION_2,
  [RESULT_CATEGORIES.CONDITION_3]: PROPERTY_TYPES.CONDITION_3
};

export const HEADER_LABELS = {
  [RELEASE_TYPES.RELEASE]: 'Release',
  [RELEASE_TYPES.RELEASE_WITH_CONDITIONS]: 'Release with Conditions',
  [RELEASE_TYPES.MAXIMUM_CONDITIONS]: 'Maximum conditions for any Release'
};

export const CONDITION_LABELS = {
  [CONDITION_TYPES.PR]: 'PR',
  [CONDITION_TYPES.PR_RELEASE]: 'PR - Release',
  [CONDITION_TYPES.EM_OR_BOND]: 'EM or $ Bond',
  [CONDITION_TYPES.EM_AND_BOND]: 'EM and $ Bond',
  [CONDITION_TYPES.CHECKIN_WEEKLY]: 'Weekly check-in',
  [CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST]: 'At least weekly check-in',
  [CONDITION_TYPES.CHECKIN_MONTHLY]: '1/month check-in',
  [CONDITION_TYPES.CHECKIN_TWICE_MONTHLY]: '2/month check-in',
  [CONDITION_TYPES.IF_APPLICABLE_247]: '24/7, if applicable',
  [CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW]: 'Hold pending judicial review'
};

// NCA score -> FTA score -> PSA CONTEXT
export const DMF_RESULTS :Object = {
  1: {
    1: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 0,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR_RELEASE
      }
    },
    2: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 0,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR_RELEASE
      }
    }
  },
  2: {
    1: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 0,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR_RELEASE
      }
    },
    2: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 0,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR_RELEASE
      }
    },
    3: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 0,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR_RELEASE
      }
    },
    4: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.DARK_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 0,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR_RELEASE
      }
    },
    5: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    }
  },
  3: {
    2: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_MONTHLY
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_MONTHLY
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_MONTHLY
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_MONTHLY
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    },
    3: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_MONTHLY
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_MONTHLY
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_MONTHLY
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_MONTHLY
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    },
    4: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_MONTHLY
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_MONTHLY
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_MONTHLY
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_MONTHLY
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.LIGHT_GREEN,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 1,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    },
    5: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    }
  },
  4: {
    2: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_TWICE_MONTHLY,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_TWICE_MONTHLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_TWICE_MONTHLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_TWICE_MONTHLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    },
    3: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_TWICE_MONTHLY,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_TWICE_MONTHLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_TWICE_MONTHLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_TWICE_MONTHLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    },
    4: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.PR,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_TWICE_MONTHLY,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_TWICE_MONTHLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_TWICE_MONTHLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_TWICE_MONTHLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.YELLOW,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 2,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    },
    5: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_OR_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    },
    6: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_AND_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    }
  },
  5: {
    2: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_OR_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    },
    3: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_OR_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    },
    4: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_OR_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    },
    5: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_OR_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.ORANGE,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.RELEASE_WITH_CONDITIONS,
        [RESULT_CATEGORIES.CONDITIONS_LEVEL]: 3,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    },
    6: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_AND_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    }
  },
  6: {
    3: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_AND_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    },
    4: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_AND_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    },
    5: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_AND_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    },
    6: {
      [CONTEXT.COURT_PENN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.EM_AND_BOND,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_3]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_MINN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.COURT_LINCOLN]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.DEMO_ORG]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.CHECKIN_WEEKLY_AT_LEAST,
        [RESULT_CATEGORIES.CONDITION_2]: CONDITION_TYPES.IF_APPLICABLE_247
      },
      [CONTEXT.BOOKING]: {
        [RESULT_CATEGORIES.COLOR]: COLORS.RED,
        [RESULT_CATEGORIES.RELEASE_TYPE]: RELEASE_TYPES.MAXIMUM_CONDITIONS,
        [RESULT_CATEGORIES.CONDITION_1]: CONDITION_TYPES.HOLD_PENDING_JUDICIAL_REVIEW
      }
    }
  }
};
