/*
 * @flow
 */
import { APP_TYPES, PROPERTY_TYPES } from './DataModelConsts';

const {
  ARREST_CASES,
  BONDS,
  MANUAL_PRETRIAL_CASES,
  MANUAL_PRETRIAL_COURT_CASES,
  OUTCOMES,
  PEOPLE,
  PSA_SCORES,
  PSA_RISK_FACTORS,
  RCM_BOOKING_CONDITIONS,
  RCM_COURT_CONDITIONS,
  RCM_RESULTS,
  RCM_RISK_FACTORS,
  RELEASE_CONDITIONS,
  RELEASE_RECOMMENDATIONS,
  STAFF,
  CHARGES,
  MANUAL_CHARGES,
  MANUAL_COURT_CHARGES
} = APP_TYPES;

const DOWNLOAD_CONFIG :Object = {
  /* People */
  [PEOPLE]: {
    [PROPERTY_TYPES.LAST_NAME]: 'LAST',
    [PROPERTY_TYPES.FIRST_NAME]: 'FIRST',
    [PROPERTY_TYPES.MIDDLE_NAME]: 'MIDDLE',
    [PROPERTY_TYPES.SEX]: 'SEX',
    [PROPERTY_TYPES.DOB]: 'DOB',
    [PROPERTY_TYPES.RACE]: 'RACE',
    [PROPERTY_TYPES.ETHNICITY]: 'ETHNICITY'
  },
  /* Arrest Info */
  [ARREST_CASES]: {
    [PROPERTY_TYPES.ARRESTING_AGENCY]: 'REFERRED BY',
    [PROPERTY_TYPES.CASE_ID]: 'ARREST CASE NUMBER'
  },
  [MANUAL_PRETRIAL_CASES]: {
    [PROPERTY_TYPES.ARREST_DATE_TIME]: 'ARREST DATE',
    [PROPERTY_TYPES.NUMBER_OF_CHARGES]: '# CHARGES'
  },
  [MANUAL_PRETRIAL_COURT_CASES]: {
    [PROPERTY_TYPES.ARREST_DATE_TIME]: 'ARREST DATE',
    [PROPERTY_TYPES.NUMBER_OF_CHARGES]: '# CHARGES'
  },
  [STAFF]: {
    [PROPERTY_TYPES.PERSON_ID]: 'FILER'
  },
  [PSA_SCORES]: {
    [PROPERTY_TYPES.DATE_TIME]: 'DATE FILED',
    [PROPERTY_TYPES.NVCA_FLAG]: 'NVCA',
    [PROPERTY_TYPES.FTA_SCALE]: 'FTA',
    [PROPERTY_TYPES.NCA_SCALE]: 'NCA',
    [PROPERTY_TYPES.STATUS]: 'STATUS',
    [PROPERTY_TYPES.STATUS_NOTES]: 'STATUS NOTES',
    [PROPERTY_TYPES.FAILURE_REASON]: 'FAILURE REASON',
  },
  [PSA_RISK_FACTORS]: {
    [PROPERTY_TYPES.AGE_AT_CURRENT_ARREST]: 'Q1',
    [PROPERTY_TYPES.CURRENT_VIOLENT_OFFENSE]: 'Q2',
    [PROPERTY_TYPES.CURRENT_VIOLENT_OFFENSE_NOTES]: 'Q2 NOTES',
    [PROPERTY_TYPES.CURRENT_VIOLENT_OFFENSE_AND_YOUNG]: 'Q2A',
    [PROPERTY_TYPES.PENDING_CHARGE]: 'Q3',
    [PROPERTY_TYPES.PENDING_CHARGE_NOTES]: 'Q3 NOTES',
    [PROPERTY_TYPES.PRIOR_MISDEMEANOR]: 'Q4',
    [PROPERTY_TYPES.PRIOR_MISDEMEANOR_NOTES]: 'Q4 NOTES',
    [PROPERTY_TYPES.PRIOR_FELONY]: 'Q5',
    [PROPERTY_TYPES.PRIOR_FELONY_NOTES]: 'Q5 NOTES',
    [PROPERTY_TYPES.PRIOR_CONVICTION]: 'Q5A',
    [PROPERTY_TYPES.PRIOR_VIOLENT_CONVICTION]: 'Q6',
    [PROPERTY_TYPES.PRIOR_VIOLENT_CONVICTION_NOTES]: 'Q6 NOTES',
    [PROPERTY_TYPES.PRIOR_FAILURE_TO_APPEAR_RECENT]: 'Q7',
    [PROPERTY_TYPES.PRIOR_FAILURE_TO_APPEAR_RECENT_NOTES]: 'Q7 NOTES',
    [PROPERTY_TYPES.PRIOR_FAILURE_TO_APPEAR_OLD]: 'Q8',
    [PROPERTY_TYPES.PRIOR_FAILURE_TO_APPEAR_OLD_NOTES]: 'Q8 NOTES',
    [PROPERTY_TYPES.PRIOR_SENTENCE_TO_INCARCERATION]: 'Q9',
    [PROPERTY_TYPES.PRIOR_SENTENCE_TO_INCARCERATION_NOTES]: 'Q9 NOTES',
  },
  [RELEASE_RECOMMENDATIONS]: {
    [PROPERTY_TYPES.RELEASE_RECOMMENDATION]: 'NOTES'
  },
  [RCM_RESULTS]: {
    [PROPERTY_TYPES.COLOR]: 'PSA COLOR',
    [PROPERTY_TYPES.RELEASE_TYPE]: 'RELEASE TYPE',
    [PROPERTY_TYPES.CONDITIONS_LEVEL]: 'COND LVL',
    [PROPERTY_TYPES.CONDITION_1]: 'REL COND 1',
    [PROPERTY_TYPES.CONDITION_2]: 'REL COND 2',
    [PROPERTY_TYPES.CONDITION_3]: 'REL COND 3',
    [PROPERTY_TYPES.OUTCOME]: 'LEGACY JUDGE OUTCOME',
  },
  [OUTCOMES]: {
    [PROPERTY_TYPES.OUTCOME]: 'JUDGE_OUTCOME'
  },
  [BONDS]: {
    [PROPERTY_TYPES.BOND_TYPE]: 'BOND TYPE',
    [PROPERTY_TYPES.BOND_AMOUNT]: 'BOND AMOUNT',
    [PROPERTY_TYPES.SURETY_AMOUNT]: 'SURETY AMOUNT',
  },
  [RELEASE_CONDITIONS]: [
    PROPERTY_TYPES.TYPE,
    PROPERTY_TYPES.START_DATE,
    PROPERTY_TYPES.FREQUENCY
  ],
  [RCM_BOOKING_CONDITIONS]: [
    PROPERTY_TYPES.TYPE,
    PROPERTY_TYPES.START_DATE,
    PROPERTY_TYPES.FREQUENCY
  ],
  [RCM_COURT_CONDITIONS]: [
    PROPERTY_TYPES.TYPE,
    PROPERTY_TYPES.START_DATE,
    PROPERTY_TYPES.FREQUENCY
  ],
  [CHARGES]: [
    PROPERTY_TYPES.CHARGE_STATUTE,
    PROPERTY_TYPES.CHARGE_DESCRIPTION
  ],
  [MANUAL_CHARGES]: [
    PROPERTY_TYPES.CHARGE_STATUTE,
    PROPERTY_TYPES.CHARGE_DESCRIPTION
  ],
  [MANUAL_COURT_CHARGES]: [
    PROPERTY_TYPES.CHARGE_STATUTE,
    PROPERTY_TYPES.CHARGE_DESCRIPTION
  ],
  [RCM_RISK_FACTORS]: {
    [PROPERTY_TYPES.CONTEXT]: 'PSA TYPE',
    [PROPERTY_TYPES.EXTRADITED]: 'EXTRADITED',
    [PROPERTY_TYPES.EXTRADITED_NOTES]: 'EXTRADITED NOTES',
    [PROPERTY_TYPES.RCM_STEP_2_CHARGES]: 'STEP 2 CHARGES',
    [PROPERTY_TYPES.RCM_STEP_2_CHARGES_NOTES]: 'STEP 2 NOTES',
    [PROPERTY_TYPES.RCM_STEP_4_CHARGES]: 'STEP 4 CHARGES',
    [PROPERTY_TYPES.RCM_STEP_4_CHARGES_NOTES]: 'STEP 4 NOTES',
    [PROPERTY_TYPES.RCM_SECONDARY_RELEASE_CHARGES]: 'BOOKING RELEASE',
    [PROPERTY_TYPES.RCM_SECONDARY_RELEASE_CHARGES_NOTES]: 'BOOKING RELEASE NOTES',
    [PROPERTY_TYPES.RCM_SECONDARY_HOLD_CHARGES]: 'BOOKING HOLD',
    [PROPERTY_TYPES.RCM_SECONDARY_HOLD_CHARGES_NOTES]: 'BOOKING HOLD NOTES',
  },
};

export default DOWNLOAD_CONFIG;
