/*
 * @flow
 */

export const DOWNLOAD_PSA_FORMS_REQUEST :string = 'DOWNLOAD_PSA_FORMS_REQUEST';
export const DOWNLOAD_PSA_FORMS_SUCCESS :string = 'DOWNLOAD_PSA_FORMS_SUCCESS';
export const DOWNLOAD_PSA_FORMS_FAILURE :string = 'DOWNLOAD_PSA_FORMS_FAILURE';
