/*
 * @flow
 */

export const LOAD_PERSON_DATA_MODEL_REQUEST :string = 'LOAD_PERSON_DATA_MODEL_REQUEST';
export const LOAD_PERSON_DATA_MODEL_SUCCESS :string = 'LOAD_PERSON_DATA_MODEL_SUCCESS';
export const LOAD_PERSON_DATA_MODEL_FAILURE :string = 'LOAD_PERSON_DATA_MODEL_FAILURE';

export const LOAD_PRETRIAL_DATA_MODEL_REQUEST :string = 'LOAD_PRETRIAL_DATA_MODEL_REQUEST';
export const LOAD_PRETRIAL_DATA_MODEL_SUCCESS :string = 'LOAD_PRETRIAL_DATA_MODEL_SUCCESS';
export const LOAD_PRETRIAL_DATA_MODEL_FAILURE :string = 'LOAD_PRETRIAL_DATA_MODEL_FAILURE';

export const LOAD_RISK_FACTORS_DATA_MODEL_REQUEST :string = 'LOAD_RISK_FACTORS_DATA_MODEL_REQUEST';
export const LOAD_RISK_FACTORS_DATA_MODEL_SUCCESS :string = 'LOAD_RISK_FACTORS_DATA_MODEL_SUCCESS';
export const LOAD_RISK_FACTORS_DATA_MODEL_FAILURE :string = 'LOAD_RISK_FACTORS_DATA_MODEL_FAILURE';

export const LOAD_PSA_DATA_MODEL_REQUEST :string = 'LOAD_PSA_DATA_MODEL_REQUEST';
export const LOAD_PSA_DATA_MODEL_SUCCESS :string = 'LOAD_PSA_DATA_MODEL_SUCCESS';
export const LOAD_PSA_DATA_MODEL_FAILURE :string = 'LOAD_PSA_DATA_MODEL_FAILURE';

export const LOAD_RELEASE_RECOMMENDATION_DATA_MODEL_REQUEST :string = 'LOAD_RELEASE_RECOMMENDATION_DATA_MODEL_REQUEST';
export const LOAD_RELEASE_RECOMMENDATION_DATA_MODEL_SUCCESS :string = 'LOAD_RELEASE_RECOMMENDATION_DATA_MODEL_SUCCESS';
export const LOAD_RELEASE_RECOMMENDATION_DATA_MODEL_FAILURE :string = 'LOAD_RELEASE_RECOMMENDATION_DATA_MODEL_FAILURE';

export const LOAD_STAFF_DATA_MODEL_REQUEST :string = 'LOAD_STAFF_DATA_MODEL_REQUEST';
export const LOAD_STAFF_DATA_MODEL_SUCCESS :string = 'LOAD_STAFF_DATA_MODEL_SUCCESS';
export const LOAD_STAFF_DATA_MODEL_FAILURE :string = 'LOAD_STAFF_DATA_MODEL_FAILURE';

export const LOAD_CALCULATED_FOR_DATA_MODEL_REQUEST :string = 'LOAD_CALCULATED_FOR_DATA_MODEL_REQUEST';
export const LOAD_CALCULATED_FOR_DATA_MODEL_SUCCESS :string = 'LOAD_CALCULATED_FOR_DATA_MODEL_SUCCESS';
export const LOAD_CALCULATED_FOR_DATA_MODEL_FAILURE :string = 'LOAD_CALCULATED_FOR_DATA_MODEL_FAILURE';

export const LOAD_ASSESSED_BY_DATA_MODEL_REQUEST :string = 'LOAD_ASSESSED_BY_DATA_MODEL_REQUEST';
export const LOAD_ASSESSED_BY_DATA_MODEL_SUCCESS :string = 'LOAD_ASSESSED_BY_DATA_MODEL_SUCCESS';
export const LOAD_ASSESSED_BY_DATA_MODEL_FAILURE :string = 'LOAD_ASSESSED_BY_DATA_MODEL_FAILURE';

export const SEARCH_PEOPLE_REQUEST :string = 'SEARCH_PEOPLES_REQUEST';
export const SEARCH_PEOPLE_SUCCESS :string = 'SEARCH_PEOPLES_SUCCESS';
export const SEARCH_PEOPLE_FAILURE :string = 'SEARCH_PEOPLES_FAILURE';

export const LOAD_NEIGHBORS_REQUEST :string = 'LOAD_NEIGHBORS_REQUEST';
export const LOAD_NEIGHBORS_SUCCESS :string = 'LOAD_NEIGHBORS_SUCCESS';
export const LOAD_NEIGHBORS_FAILURE :string = 'LOAD_NEIGHBORS_FAILURE';

export const SUBMIT_DATA_REQUEST :string = 'SUBMIT_DATA_REQUEST';
export const SUBMIT_DATA_SUCCESS :string = 'SUBMIT_DATA_SUCCESS';
export const SUBMIT_DATA_FAILURE :string = 'SUBMIT_DATA_FAILURE';

export const SELECT_PERSON :string = 'SELECT_PERSON';
export const SELECT_PRETRIAL :string = 'SELECT_PRETRIAL';
export const CLEAR_FORM :string = 'CLEAR_FORM';

export const UPDATE_RECOMMENDATION_REQUEST :string = 'UPDATE_RECOMMENDATION_REQUEST';
export const UPDATE_RECOMMENDATION_SUCCESS :string = 'UPDATE_RECOMMENDATION_SUCCESS';
export const UPDATE_RECOMMENDATION_FAILURE :string = 'UPDATE_RECOMMENDATION_FAILURE';

export const SET_PSA_VALUE :string = 'SET_PSA_VALUE';
export const SET_PSA_VALUES :string = 'SET_PSA_VALUES';
