/*
 * @flow
 */
import { APP_TYPES, PROPERTY_TYPES } from '../DataModelConsts';

export const HEADERS = {
  LAST_NAME: `${PROPERTY_TYPES.LAST_NAME}|${APP_TYPES.PEOPLE}`,
  FIRST_NAME: `${PROPERTY_TYPES.FIRST_NAME}|${APP_TYPES.PEOPLE}`,
  MIDDLE_NAME: `${PROPERTY_TYPES.MIDDLE_NAME}|${APP_TYPES.PEOPLE}`,
  DOB: `${PROPERTY_TYPES.DOB}|${APP_TYPES.PEOPLE}`,
  INMATE_NO: `${PROPERTY_TYPES.ID}|${APP_TYPES.JAIL_STAYS}`,
  DAYS_IN_CUSTODY: `${PROPERTY_TYPES.START_DATE_TIME}|${APP_TYPES.JAIL_STAYS}`,
  COMPLETE_CHARGES: `complete|${APP_TYPES.CHARGES}`,
  PENDING_CHARGES: `pending|${APP_TYPES.CHARGES}`,
  ARREST_BONDS: APP_TYPES.ARREST_BONDS
};

export const HEADERS_OBJ = {
  [HEADERS.LAST_NAME]: 'LAST',
  [HEADERS.FIRST_NAME]: 'FIRST',
  [HEADERS.MIDDLE_NAME]: 'MIDDLE',
  [HEADERS.DOB]: 'DOB',
  [HEADERS.DAYS_IN_CUSTODY]: 'DAYS IN CUSTODY',
  [HEADERS.COMPLETE_CHARGES]: 'COMPLETE CHARGES',
  [HEADERS.PENDING_CHARGES]: 'PENDING CHARGES'
};

export const POSITIONS = Object.values(HEADERS_OBJ);
