export default {
  CASE_ID: 'CASE ID',
  COUNTY: 'COUNTY',
  COURTROOM: 'COURTROOM',
  DATE: 'DATE',
  DOB: 'DOB',
  ETHNICITY: 'ETHNICITY',
  FIRST_NAME: 'FIRST',
  HEARING_DATE: 'HEARING DATE',
  HEARING_TYPE: 'HEARING TYPE',
  LAST_NAME: 'LAST',
  MIDDLE_NAME: 'MIDDLE',
  RACE: 'RACE',
  SEX: 'SEX',
  TYPE: 'TYPE',
  WAS_NOTIFIED: 'WAS_NOTIFIED'
};
