/*
 * @flow
 */
import { APP_TYPES, PROPERTY_TYPES } from '../consts/DataModelConsts';
import DOWNLOAD_HEADERS from './DownloadHeaders';

const {
  COUNTIES,
  HEARINGS,
  PEOPLE,
  BONDS,
  JUDGES,
  OUTCOMES,
  PRETRIAL_CASES,
  PSA_SCORES,
  RELEASE_CONDITIONS
} = APP_TYPES;

const HEARINGS_CONFIG :Object = {
  /* Hearings */
  [HEARINGS]: {
    [PROPERTY_TYPES.CASE_ID]: DOWNLOAD_HEADERS.CASE_ID,
    [PROPERTY_TYPES.DATE_TIME]: DOWNLOAD_HEADERS.HEARING_DATE,
    [PROPERTY_TYPES.COURTROOM]: DOWNLOAD_HEADERS.COURTROOM,
    [PROPERTY_TYPES.HEARING_TYPE]: DOWNLOAD_HEADERS.HEARING_TYPE,
  },
  /* Judges */
  [JUDGES]: {
    [PROPERTY_TYPES.LAST_NAME]: DOWNLOAD_HEADERS.JUDGE_LAST_NAME,
    [PROPERTY_TYPES.FIRST_NAME]: DOWNLOAD_HEADERS.JUDGE_FIRST_NAME,
  },
  /* People */
  [PEOPLE]: {
    [PROPERTY_TYPES.LAST_NAME]: DOWNLOAD_HEADERS.LAST_NAME,
    [PROPERTY_TYPES.FIRST_NAME]: DOWNLOAD_HEADERS.FIRST_NAME,
    [PROPERTY_TYPES.PERSON_ID]: DOWNLOAD_HEADERS.PARTY_ID,
  },
  /* Outcomes */
  [OUTCOMES]: {
    [PROPERTY_TYPES.OUTCOME]: DOWNLOAD_HEADERS.OUTCOME,
    [PROPERTY_TYPES.OTHER_TEXT]: DOWNLOAD_HEADERS.OUTCOME_NOTES,
  },
  /* Bonds */
  [BONDS]: {
    [PROPERTY_TYPES.BOND_TYPE]: DOWNLOAD_HEADERS.BOND_TYPE,
    [PROPERTY_TYPES.BOND_AMOUNT]: DOWNLOAD_HEADERS.BOND_AMOUNT,
  },
  /* PSA Scores */
  [PSA_SCORES]: {
    [PROPERTY_TYPES.FTA_SCALE]: 'FTA',
    [PROPERTY_TYPES.NCA_SCALE]: 'NCA',
    [PROPERTY_TYPES.NVCA_FLAG]: 'NVCA',
  },
  /* Pretrial Case */
  [PRETRIAL_CASES]: {
    [PROPERTY_TYPES.CASE_ID]: DOWNLOAD_HEADERS.PRETRIAL_CASE_ID
  },
  /* Release Conditions */
  [RELEASE_CONDITIONS]: [
    PROPERTY_TYPES.TYPE,
    PROPERTY_TYPES.START_DATE,
    PROPERTY_TYPES.FREQUENCY
  ],
  /* County */
  [COUNTIES]: {
    [PROPERTY_TYPES.NAME]: DOWNLOAD_HEADERS.COUNTY
  }
};

export default HEARINGS_CONFIG;
