/*
 * @flow
 */
import { APP_TYPES, PROPERTY_TYPES } from '../consts/DataModelConsts';

const {
  COUNTIES,
  HEARINGS,
  MANUAL_REMINDERS,
  PEOPLE,
  REMINDERS
} = APP_TYPES;

const REMINDERS_CONFIG :Object = {
  /* Reminders */
  [REMINDERS]: {
    [PROPERTY_TYPES.DATE_TIME]: 'DATE',
    [PROPERTY_TYPES.NOTIFIED]: 'WAS NOTIFIED'
  },
  /* Manual Reminders */
  [MANUAL_REMINDERS]: {
    [PROPERTY_TYPES.DATE_TIME]: 'DATE',
    [PROPERTY_TYPES.NOTIFIED]: 'WAS NOTIFIED'
  },
  /* People */
  [PEOPLE]: {
    [PROPERTY_TYPES.LAST_NAME]: 'LAST',
    [PROPERTY_TYPES.FIRST_NAME]: 'FIRST',
    [PROPERTY_TYPES.MIDDLE_NAME]: 'MIDDLE',
    [PROPERTY_TYPES.SEX]: 'SEX',
    [PROPERTY_TYPES.DOB]: 'DOB',
    [PROPERTY_TYPES.RACE]: 'RACE',
    [PROPERTY_TYPES.ETHNICITY]: 'ETHNICITY'
  },
  /* HEARINGS */
  [HEARINGS]: {
    [PROPERTY_TYPES.CASE_ID]: 'CASE ID',
    [PROPERTY_TYPES.DATE_TIME]: 'HEARING DATE',
    [PROPERTY_TYPES.COURTROOM]: 'COURTROOM',
    [PROPERTY_TYPES.HEARING_TYPE]: 'HEARING TYPE',
  },
  /* HEARINGS */
  [COUNTIES]: {
    [PROPERTY_TYPES.NAME]: 'COUNTY'
  }
};

export default REMINDERS_CONFIG;
