/*
 * @flow
 */
import { APP_TYPES, PROPERTY_TYPES } from '../consts/DataModelConsts';
import DOWNLOAD_HEADERS from './DownloadHeaders';

const {
  CONTACT_INFORMATION,
  COUNTIES,
  HEARINGS,
  MANUAL_REMINDERS,
  PEOPLE,
  REMINDERS
} = APP_TYPES;

const REMINDERS_CONFIG :Object = {
  /* Reminders */
  [REMINDERS]: {
    [PROPERTY_TYPES.DATE_TIME]: DOWNLOAD_HEADERS.DATE,
    [PROPERTY_TYPES.NOTIFIED]: DOWNLOAD_HEADERS.WAS_NOTIFIED,
    [PROPERTY_TYPES.TYPE]: DOWNLOAD_HEADERS.TYPE
  },
  /* Manual Reminders */
  [MANUAL_REMINDERS]: {
    [PROPERTY_TYPES.DOCKET_NUMBER]: DOWNLOAD_HEADERS.DOCKET_NUMBER,
    [PROPERTY_TYPES.DATE_TIME]: DOWNLOAD_HEADERS.DATE,
    [PROPERTY_TYPES.NOTIFIED]: DOWNLOAD_HEADERS.WAS_NOTIFIED,
    [PROPERTY_TYPES.TYPE]: DOWNLOAD_HEADERS.TYPE
  },
  /* Manual Reminders */
  [CONTACT_INFORMATION]: {
    [PROPERTY_TYPES.PHONE]: DOWNLOAD_HEADERS.CONTACT,
    [PROPERTY_TYPES.EMAIL]: DOWNLOAD_HEADERS.CONTACT
  },
  /* People */
  [PEOPLE]: {
    [PROPERTY_TYPES.LAST_NAME]: DOWNLOAD_HEADERS.LAST_NAME,
    [PROPERTY_TYPES.FIRST_NAME]: DOWNLOAD_HEADERS.FIRST_NAME,
    [PROPERTY_TYPES.MIDDLE_NAME]: DOWNLOAD_HEADERS.MIDDLE_NAME,
    [PROPERTY_TYPES.SEX]: DOWNLOAD_HEADERS.SEX,
    [PROPERTY_TYPES.DOB]: DOWNLOAD_HEADERS.DOB,
    [PROPERTY_TYPES.RACE]: DOWNLOAD_HEADERS.RACE,
    [PROPERTY_TYPES.ETHNICITY]: DOWNLOAD_HEADERS.ETHNICITY
  },
  /* HEARINGS */
  [HEARINGS]: {
    [PROPERTY_TYPES.CASE_ID]: DOWNLOAD_HEADERS.CASE_ID,
    [PROPERTY_TYPES.DATE_TIME]: DOWNLOAD_HEADERS.HEARING_DATE,
    [PROPERTY_TYPES.COURTROOM]: DOWNLOAD_HEADERS.COURTROOM,
    [PROPERTY_TYPES.HEARING_TYPE]: DOWNLOAD_HEADERS.HEARING_TYPE,
  },
  /* HEARINGS */
  [COUNTIES]: {
    [PROPERTY_TYPES.NAME]: DOWNLOAD_HEADERS.COUNTY
  }
};

export default REMINDERS_CONFIG;
