export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const ENROLL_VOICE_REQUEST = 'ENROLL_VOICE_REQUEST';
export const ENROLL_VOICE_SUCCESS = 'ENROLL_VOICE_SUCCESS';
export const ENROLL_VOICE_FAILURE = 'ENROLL_VOICE_FAILURE';

export const CLEAR_ERROR = 'CLEAR_ERROR';
